### ISSUE TITLE
Mis-encoded text at the bottom of the installer GUI

### ISSUE THREAD

**Issue by DavidEGrayson** [ARMmbed/yotta_windows_installer#12] opened 2015-10-12 20:01 UTC
I was watching your [Youtube video showing the installer](https://www.youtube.com/watch?v=4fqiHUyyXvU) and I noticed that there is some mis-encoded text shown in the installer at time [0:32](http://www.youtube.com/watch?v=4fqiHUyyXvU&t=0m32s).  It looks like a copyright and/or trademark symbol is getting mangled.

**Comment by BlackstoneEngineering** [comment] 2015-10-13 00:13
Good catch! I'm aware of the bug and have tried a couple different ways around it but to no avail, most likely need to re-compile the binary with the unicode support version of NSIS (default version doesn't have it). 

If you can figure it out PR's are always welcome!

**Comment by BlackstoneEngineering** [comment] 2015-10-24 22:32
Closing this as its a duplicate of this https://github.com/ARMmbed/yotta_windows_installer/issues/10 issue

**Closed by BlackstoneEngineering** 2015-10-24 22:32 UTC
